[package]
name = "Rusttp-Server"
version = "0.1.0"
authors = ["Kiefer <kiefx@pm.me>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
brotli = "8.0.2"
libflate = "2.1.0"
threadpool = "1.8.1"
titlecase = "=3.6.0"